package de.uni_leipzig.simba.saim.gui.widget;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.Panel;

import de.uni_leipzig.simba.data.Mapping;

public class InstanceWindow extends Panel {

		
	@AutoGenerated
	private Layout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public InstanceWindow() {
		super();
		buildMainLayout();
		this.setContent(mainLayout);
		
		Mapping m = new Mapping();
		for(int i = 0;  i<10; i++) {
			m.add("a"+i, "b"+i, 1.0);
			m.add("b"+i, "b"+i, 3.0);
			m.add("c"+i, "b"+i, 1.0);
			m.add("d"+i, "b"+i, 5.0);
			m.add("e"+i, "b"+i, 1.0);
			m.add("aa"+i, "b"+i, 1.0);
			m.add("bb"+i, "b"+i, 8.0);
			m.add("cc"+i, "b"+i, 1.0);
		}
		InstanceMappingTable mapTable = new InstanceMappingTable(m);
		addComponent(mapTable.getFlatTable());
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new HorizontalLayout();
	}

}
