package de.uni_leipzig.simba.saim.gui.widget.window;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;

import de.uni_leipzig.simba.saim.Messages;

public class About extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = -1635796226509916356L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet About;
	@AutoGenerated
	private RichTextArea impressum;
	@AutoGenerated
	private Label about;
	final Messages messages;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public About(final Messages messages) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		this.messages = messages;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// About
		About = buildAbout();
		mainLayout.addComponent(About,
				"top:0.0px;right:1.0px;bottom:-4.0px;left:1.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildAbout() {
		// common part: create layout
		About = new TabSheet();
		About.setImmediate(true);
		About.setWidth("100.0%");
		About.setHeight("100.0%");
		
		// about
		about = new Label(this.getAboutContent());
		about.setVisible(true);

		about.setWidth("100.0%");
		about.setHeight("100.0%");
		
		about.setContentMode(Label.CONTENT_XHTML);
		About.addTab(about, "About", null);
		
		
//		// impressum
//		impressum = new RichTextArea();
//		impressum.setEnabled(false);
//		impressum.setImmediate(false);
//		impressum.setVisible(false);
//		impressum.setWidth("100.0%");
//		impressum.setHeight("100.0%");
//		About.addTab(impressum, "Impressum", null);
		
		return About;
	}
	
	/**
	 * Generate content of the About RichTextField.
	 * @return RichText Content of the about component.
	 */
	private String getAboutContent() {
		String s = "<h1>SAIM Instance Matching Application</h1>" +
				"SAIM is an web interface for the <a href='http://aksw.org/Projects/LIMES.html'>LIMES</a> linking framework.</br>" +
				"<h1>Team</h1>" +
				"<ul>" +
				" <li><a href='http://aksw.org/AxelNgonga.html'>Dr. Axel-C. Ngonga Ngomo</a></li>" +
				" <li><a href='http://aksw.org/KonradHoeffner.html'>Konrad Höffner</a></li>" +
				" <li>René Speck</li>" +
				" <li>Klaus Lyko</li>" +
				"</ul>";		
		return s;
	}

}
