package de.uni_leipzig.simba.saim.gui.widget.window;

import com.vaadin.annotations.AutoGenerated;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

import de.uni_leipzig.simba.data.Mapping;
import de.uni_leipzig.simba.saim.SAIMApplication;
import de.uni_leipzig.simba.util.DataCleaner;

import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Select;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

import de.uni_leipzig.simba.saim.SAIMApplication;
import de.uni_leipzig.simba.saim.util.LinkQualityComputer;

public class ValidateLinksWindow extends CustomComponent {
	private final String storageFile = "reference.list";
	SAIMApplication app;
	private VerticalLayout mainLayout;
	Select refSelect;
	private HashMap<String, String> examples;
	private Button compare;
	Mapping mapping;
	
	public ValidateLinksWindow(SAIMApplication app, Mapping mapping) {
		
		this.app = app;
		this.mapping = mapping;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	
	private void buildMainLayout() {		
		mainLayout = new VerticalLayout();
		try {
			refSelect = loadReferenceFile();
			compare = new Button("Start comparing...");
			compare.addListener(new CompareClickListener(app));
			mainLayout.addComponent(refSelect);
			mainLayout.addComponent(compare);
		} catch (IOException | URISyntaxException e) {
			app.getMainWindow().showNotification("Error loading reference files");
			e.printStackTrace();
		}
	}

	
	private void init() {
		
	}
	
	/**
	 * Generates Select for gold standard files.
	 * @return Select with Listener;
	 * @throws IOException
	 * @throws URISyntaxException
	 */
	private Select loadReferenceFile() throws IOException, URISyntaxException {
		Select select = new Select("Compare to available gold standards:");
		// load list
		URL url;String path;examples=new HashMap<String,String>();
		url = getClass().getClassLoader().getResource(storageFile);
		path = new File(url.toURI()).getAbsolutePath();
		InputStreamReader inputStreamReader = new InputStreamReader(new FileInputStream (path));
		BufferedReader bufferedReader = new BufferedReader (inputStreamReader);
		String line = bufferedReader.readLine();
		while(line != null) {
			String parts[] = DataCleaner.separate(line, ";", 2);
			if(line.length()>0 && parts.length==2) {
				String name=parts[0].replaceAll("\"", "");
				examples.put(name, parts[1].replaceAll("\"", ""));
				select.addItem(name);
				line = bufferedReader.readLine();				
			}
		}
		bufferedReader.close();inputStreamReader.close();
		return select;
	}
	
	
	class CompareClickListener implements Button.ClickListener {
		SAIMApplication app;
		
		public CompareClickListener(SAIMApplication app) {
			this.app = app;
		}
		@Override
		public void buttonClick(ClickEvent event) {
			String path = examples.get(refSelect.getValue());
			URL url = getClass().getClassLoader().getResource(path);
			System.out.println(url.getPath()+","+url.getFile());
			Mapping ref = LinkQualityComputer.getMapping(url.getPath());
			System.out.println(ref);
			LinkQualityComputer lc = new LinkQualityComputer(mapping, ref);
			System.out.println("f="+lc.computeFScore()+" p="+lc.computePrecision()+" r="+lc.computeRecall());
			Window sub = new Window("Qualtity of mapping...");
			Label label = new Label("F-score="+lc.computeFScore()+"<br>Precision="+lc.computePrecision()+"<br>Recall="+lc.computeRecall(), Label.CONTENT_XHTML);
			sub.addComponent(label);
			app.getMainWindow().addWindow(sub);
		}
		
	}
}
